config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :user_sessions

  resources :passes do 
    resources :localities, shallow: true
  end
  get 'passes_map' => 'passes#map', :as => :passes_map

  resources :regions, shallow: true do
    resources :provinces, shallow: true do
      resources :municipalities, shallow: true do
        get 'infobox' => 'municipalities#infobox', :as => :infobox
        resources :fractions, shallow: true
      end
    end
  end
  get 'municipalities_map' => 'municipalities#map', :as => :municipalities_map

  resources :brands, shallow: true do 
    resources :models, shallow: true do
      resources :bikes, shallow: true do
        resources :pictures, shallow: true
      end
    end
  end
  resources :categories

  
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'static#index'

end

app/models/db_passes/db_passi_panoramio_picture.rb
class DbPassiPanoramioPicture < ActiveRecord::Base
  include ConnectToDbPasses
  belongs_to :picturable, polymorphic: true
  self.table_name = 'flickr_pictures'
end

app/models/db_passes/locality.rb
class Locality < ActiveRecord::Base
  include ConnectToDbPasses
  belongs_to :pass
  belongs_to :localitiable, polymorphic: true
  
end

app/models/db_passes/pass.rb
class Pass < ActiveRecord::Base
  include ConnectToDbPasses
  include Searchable
  include Geolocable

  has_many :pictures, :class_name => "DbPassiPanoramioPicture", as: :picturable, dependent: :destroy

  def address
    address = self.name 
    if !self.localities.empty?
      loc = self.localities.first
      address = address + ", " + loc.municipality.province.name + ", " + loc.municipality.province.region.name if loc.class.name == "Fraction"
      address = address + ", " + loc.province.name + ", " + loc.province.region.name if loc.class.name == "Municipality"
    end
    return address + ", Italy"
  end

  def localities
    result = []
    Locality.where(:pass_id => self.id).each do |locality|
      result = result << locality.localitiable
    end
    return result
  end

end

app/controllers/db_passes/db_passes_controller.rb
class DbPassesController < ApplicationController
  prepend_view_path("app/views/db_passes")
end

app/controllers/db_passes/localities_controller.rb
class LocalitiesController < DbPassesController
	# GET /passes
  # GET /passes.json
  def index
    @localities = Locality.where(:pass_id => params[:pass_id])
    @list = []
    @localities.each do |locality|
      @list << getLocality(locality)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list }
    end
  end

  # GET /passes/1
  # GET /passes/1.json
  def show
    @locality = Locality.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /passes/new
  # GET /passes/new.json
  def new
    @locality = Locality.new

    @pass = nil
    if params[:pass_id]
      @pass = Pass.find(params[:pass_id].to_i)
    else
      @pass = Pass.all.first
    end
    @object = [@pass, @locality]


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /passes/1/edit
  def edit
    @locality = Locality.find(params[:id])
    @pass = @locality.pass
    @object = @locality
  end

  # POST /passes
  # POST /passes.json
  def create
    @locality = Locality.new(params[:locality])

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render json: @locality, status: :created, location: @locality }
      else
        format.html { render action: "new" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /passes/1
  # PUT /passes/1.json
  def update
    @locality = Locality.find(params[:id])

    respond_to do |format|
      if @locality.update_attributes(params[:locality])
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passes/1
  # DELETE /passes/1.json
  def destroy
    @locality = Locality.find(params[:id])
    @pass = @locality.pass
    @locality.destroy


    respond_to do |format|
      format.html { redirect_to @pass }
      format.json { head :no_content }
    end
  end

  private

  def getLocality locality
    if locality.fraction_id.nil?
      return Municipality.find(locality.municipality_id)
    else
      return Fraction.find(locality.fraction_id)
    end
  end
end

app/controllers/db_passes/passes_controller.rb
class PassesController < DbPassesController

  # GET /passes
  # GET /passes.json
  def index
    @passes, @alphaParams = 
       Pass.all.alpha_paginate(params[:letter], {:js => true, :bootstrap3 => true}){|pass| pass.name}
    respond_to do |format|
      format.html { render "layouts/sidebar" }
      format.json { render json: @passes }
    end
  end

  def map
    @passes = Pass.where("latitude IS NOT NULL")

    @markers = Gmaps4rails.build_markers(@passes) do |pass, marker|
      marker.lat pass.latitude
      marker.lng pass.longitude
      marker.title pass.id.to_s
      marker.infowindow pass.name
    end

    respond_to do |format|
      format.html { render "layouts/sidebar" }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def pass_params
    params.require(:pass).permit(
      :name,
      :altitude,
      :latitude,
      :longitude,
      :locality)
  end

end

app/views/db_passes/passes/_form.html.erb
<%= f.input :name, :label => "Name", :placeholder => "Name" %>
<%= f.input :altitude, :label => "Altitude", :placeholder => "Altitude" %>

app/views/db_passes/passes/_index.html.erb
<%= render "layouts/header_index" %>

<div id="pagination_table">
<table class="table table-hover table-striped">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Altitude</th>
    <% if current_user %>
        <th></th>
        <th></th>
    <% end %>
  </tr>

<% @passes.each_with_index do |pass,index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= link_to pass.name, pass %></td>
    <td><%= pass.altitude %></td>
    <% if current_user %>
        <td><%= link_to 'Edit', edit_pass_path(pass), 
            :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', pass, method: :delete, 
            data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>
<br />

app/views/db_passes/passes/_map.html.erb
<div id="map"></div>

<script type="text/javascript">

handler = Gmaps.build('Google', { 
	builders: { Marker: InfoBoxBuilder},
	markers:
    {clusterer: {
      gridSize: 40,
      maxZoom: 10,
      styles: [
      	{
				height: 53,
				width: 53,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m1.png"
				},
				{
				height: 56,
				width: 56,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m2.png"
				},
				{
				height: 66,
				width: 66,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m3.png"
				},
				{
				height: 78,
				width: 78,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m4.png"
				},
				{
				height: 90,
				width: 90,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m5.png"
				}
			]
  	}
  }
});

handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @markers.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
});

</script>

<style>

  #map {
    height: 700px;
    width: 100%;
    margin: 0px;
    padding: 0px;
    min-height: 100%;
  }

  #map img { 
  	max-width: none;
	}

	#map label { 
	  width: auto; display:inline; 
	} 

	.infobox1 {
      border:1px solid #d5d5d5;
      margin-top: 8px;
      background:#fefefe;
      font-family:Arial, Helvetica, sans-serif;
      font-size:12px;
      padding: 1em;
      -webkit-border-radius: 3px;
      -moz-border-radius: 3px;
      border-radius: 3px;
      -webkit-box-shadow: 0 0  5px #acacac;
      box-shadow: 0 0 5px #acacac;
  }

  .infoBox img{
  	margin-top: 10px !important; 
		margin-right: 2px !important;
  }
</style>

app/views/db_passes/passes/show.html.erb
<div class="container-fluid">

<%= render "layouts/header_show", :title => @pass.name %> 

<div class="row">
  <div class="col-sm-6">


    <p>
      <b>Altitude:</b>
      <%= @pass.altitude %> metri
    </p>

    <p>
      <b>Latitude:</b>
      <%= @pass.latitude %>
    </p>

    <p>
      <b>Longitude:</b>
      <%= @pass.longitude %>
    </p>

    <% if current_user %>

      <br/>

      <%= link_to command_label('fa fa-edit', "Edit"), 
          edit_pass_path(@pass), :class=> "btn btn-primary" %>

      <%= link_to command_label('fa fa-trash-o', "Destroy"), 
          @pass, method: :delete, data: { confirm: 'Are you sure?' }, 
          :class => "btn btn-danger" %>
    <% end %>

    <br/><br/>

    <%= render "localities/index", :localities => @pass.localities %>
  </div>
  <div class="col-sm-6">
    <%= render "layouts/single_marker_map", :item => @pass %>
  </div>

</div>

<br/><br/>
</div>

<legend>Images</legend>
<%= render "pictures/carousel", :pictures => @pass.pictures %>